# Generated by Django 4.0.1 on 2022-01-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='category',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='created_by',
            new_name='estado_actual',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='last_updated',
            new_name='fecha_compra',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='issue_by',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='issue_to',
            new_name='persona_asignada',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='item_name',
            new_name='serial',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='phone_number',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='issue_quantity',
            new_name='valor_compra',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='export_to_CSV',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='receive_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='receive_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='reorder_level',
        ),
    ]
